### ISSUE TITLE
Video overlaps "plus" button

### ISSUE THREAD

**Issue by dagrooms52** [TabMachine/KivyTest#3]
![vidoverlap](https://cloud.githubusercontent.com/assets/8743446/10121178/07f99848-64a5-11e5-8e20-ee0bcdaa784b.png)

As depicted above, the full screen application has the video overlapping the plus button.
We may consider removing the video, since someone who installs an application for writing and viewing guitar tabs probably knows what a guitar tab is. Otherwise, we could give it its own "screen" in the application.

**Comment by mar7f7** [comment]
I moved the video back to the right. The reason this error was happening was because it was moved via pixels so when the screen was increased in size the video was moved less to the right. I also, fixed the issue of it interfering with the "powered by Kivy" text. The video will always stay a font size \* 2 (could be changed to 1, I think) above the text. As mentions we may not need this, I was just messing around when I added it. We could maybe turn it into a "trailer" for the app, talking about the cool features and how to use the app. We will see.
